server:
  port: 8888
spring:
  cloud:
    gateway:
      routes: #数组形式
        - id: user-service  #路由唯一标识
          #uri: http://127.0.0.1:8000  #想要转发到的地址
          #从nacos进行转发
          uri: lb://smart-user-service
          order: 1 #优先级，数字越小优先级越高
          #http://127.0.0.1:8888/user-server/sysUser/findById?modelId=5749761161124921344
          predicates: #断言 配置哪个路径才转发
            - Path=/user-server/**
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1  #去掉第一层前缀
      #开启网关拉取nacos的服务
      discovery:
        locator:
          enabled: true
