server:
  port: 7100
  servlet:
    context-path: /system

customer:
  ssh:
    is-use: F # 是否启用：T-启用 F-禁用
    username: ubuntu # 服务器登录用户名
    password: /Users/barryw/Documents/programs/my/ba-cloud/ba-common/src/main/resources/prvkey.pem # 服务器登录密码 或 密钥文件路径
    host: 43.138.219.96 # 服务器公网IP
    port: 22 # 跳板机ssh开放的接口   默认端口 22
    auth-type: PUBLIC_KEY # 连接方式：PUBLIC_KEY-秘钥 PASSWORD-密码
  mysql:
    host: 127.0.0.1
    port: 3306
    database: ba_cloud
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 4

spring:
  application:
    name: ba-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://${customer.mysql.host}:${customer.mysql.port}/${customer.mysql.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: ${customer.mysql.username}
      password: ${customer.mysql.password}
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: ${customer.redis.host}
    port: ${customer.redis.port}
    database: ${customer.redis.database}
    timeout: 60000
    password: ${customer.redis.password}
    lettuce:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 10 # 连接池中的最大空闲连接默认 8
        min-idle: 5  # 连接池中的最小空闲连接默认 0
# 控制台输出sql、查询下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
  httpclient:
    connection-timeout: 10000
    enabled: true
