server:
  port: 7777
spring:
  cloud:
    gateway:
      routes: #数组形式
        - id: ba-system  #路由唯一标识
          uri: http://127.0.0.1:8100  #想要转发到的地址
#          uri: lb://ba-system #从nacos进行转发
          order: 1 #优先级，数字越小优先级越高
          #http://127.0.0.1:8888/system-server/sysUser/findById?modelId=5749761161124921344
          predicates: #断言 配置哪个路径才转发
            - Path=/system-server/**
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1  #去掉第一层前缀（转发地址：lb://ba-system/**，去掉 /system-server）
            - PrefixPath=/system  # 添加前缀（转发地址：lb://ba-system/system/**，加上 /system）
        - id: ba-file
          uri: http://127.0.0.1:8101
#          uri: lb://ba-file #从nacos进行转发
          order: 1
          predicates:
            - Path=/file-server/**
          filters:
            - StripPrefix=1
            - PrefixPath=/file
      #开启网关拉取nacos的服务
      discovery:
        locator:
          enabled: false
